### PR TITLE
Update fonts from Noto -> Lato

### PR DESCRIPTION
**Pull request by nixterrimus**
## Summary:
Updates fonts so that they match the rest of Khan Academy.

Screen Shot 2023-01-05 at 10 56 20 AM

Issue: https://khanacademy.atlassian.net/browse/LP-13214

## Test plan:
- Load an exercise within the context of webapp
- **The paragraph font should use Lato**

[LP-13214]: https://khanacademy.atlassian.net/browse/LP-13214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jaredly — COMMENTED** [review]
looks like Noto Serif shows up in passage.less -- do you want to change it there too? https://github.com/Khan/perseus/blob/c40007e14ab5dffde65c95edb4f23aeade4676cd/packages/perseus/src/styles/widgets/passage.less#L41

**Comment by handeyeco** [comment]
@jaredly I'm wondering if Passage is intentionally different, since Passage is the widget that's kind of like "read this part of a book." For long stretches of text, my understanding is serif is easier on the eyes. Might be a question for a design person.

@nixterrimus Do you mind adding a before/after image to the PR?

**Comment by nixterrimus** [comment]
@jaredly I would prefer to change just what was requested for-change and wait to see if other places are needed.

**Review by handeyeco — APPROVED** [review]
Screen Shot 2023-01-05 at 3 17 26 PM

Looks like Passage is a serif in prod right now, so I'm good with merging this and then seeing what Sarah B from design thinks.

**Review by jaredly — APPROVED** [review]

**Comment by kevinbarabash** [comment]
In webapp we use `Noto` for non-latin characters.  Perhaps it should still be included as a fallback or use the same approach as webapp uses in [noto.css](https://github.com/Khan/webapp/blob/master/services/static/stylesheets/shared-package/noto.css).

**Pull request merged**
