### PR TITLE
Add ArticleRenderer stories (we didn't have any yet)

### PR DESCRIPTION
**Pull request by jeremywiebe**
## Summary:

This PR introduces a Story for the ArticleRender. We had one example in a Definition widget story, but now there's a Story for the ArticleRenderer in the Renderers area.

image

Issue: "none"

## Test plan:

`yarn storybook` and navigate to **Perseus** >> **Renderers** >> **Article Renderer**

### CODE REVIEW

**Review by SonicScrewdriver — APPROVED** [review]
Lovely, thank you greatly!

**Comment by nedredmond** [comment]
my only wish was that these changes were independent of the others so that i could merge them _right now_

**Comment by nedredmond** [comment]
Cherry-picked your commit to test things

**Comment by jeremywiebe** [comment]
> my only wish was that these changes were independent of the others so that i could merge them _right now_

@nedredmond Good call.  I did these while working on the analytics and should have pulled them out separately. I should be able to land the feature branch today so they'll be on `main` shortly. :)

**Pull request merged**
