### PR TITLE
Update WB toolbar depenency in dev

### PR DESCRIPTION
**Pull request by nishasy**
## Summary:
This check was failing on everyone's branches, so fixing it here
https://github.com/Khan/perseus/actions/runs/9088536946/job/24978356027?pr=1268

Issue: none

## Test plan:
`yarn typecheck`
`yarn run lint`

### CODE REVIEW

**Review by benchristel — COMMENTED** [review]
I think the toolbar is only used by the dev UI, right? If that's true, I'd prefer to add the dependency to `dev/package.json` if we can. Otherwise, clients of Perseus will have to install `wonder-blocks-toolbar` when nothing in Perseus itself actually needs it.

**Review by benchristel — APPROVED** [review]
LGTM! 🎉

**Comment by nishasy** [comment]
🤦🏽‍♀️ This PR isn't doing what I thought it's doing. The toolbar dependency was already there, and switching from 3.0.30 to 3.0.31 is trivial and won't actually fix the linting/typecheck issues we've been seeing.

I'm going to abandon this for now, and we can update this dependency when there's actually a need for it. I don't think I can land it anyway because of the type error that we're still trying to figure out.

**Comment by nishasy** [comment]
Cache is fixed here, so I guess I'll land it anyway

**Pull request merged**
