### PR TITLE
Remove possible unused types

### PR DESCRIPTION
**Pull request by handeyeco**
## Summary:
Do we need these? I don't think MathInput uses Hubble, JSDiff, or Raphael?

There are three left, do we need those?
- Aphrodite (shouldn't Aphrodite provide these?)
- Assets (Phospher)
- Utility (TS helpers)

### CODE REVIEW

**Review by jeremywiebe — CHANGES_REQUESTED** [review]
We still need this AFAIK.  `hubble` is used in `multi-renderer.tsx`. `jsdiff` is used in the perseus-editor package. and `raphael` is used by Graphie.

**Comment by handeyeco** [comment]
@jeremywiebe Every package has a copy of these, this is just removing these from MathInput which, AFAIK, doesn't use those. I can keep them, but I feel like we probably don't need 11 `hubble.d.ts` files.

**Comment by jeremywiebe** [comment]
> @jeremywiebe Every package has a copy of these, this is just removing these from MathInput which, AFAIK, doesn't use those. I can keep them, but I feel like we probably don't need 11 `hubble.d.ts` files.

Your changes are deleting the files in the root of the repo's `/type` folder.  This `type` folder is symlinked into each package as that is the only way for these Typescript type definitions to work properly with all the infra we have. :( So until no packages use them, these type defs have to stay, I think.

**Comment by handeyeco** [comment]
@jeremywiebe Ah, thank you for clarifying. I'll update the PR to add a README so I don't try this again in two months.

**Review by jeremywiebe — APPROVED** [review]
Thank-you for adding this README!  I shoulda dun it when I set up the symlinks originally. :(

**Pull request merged**
